inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.5.5
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/AsciiComments:
  Enabled: false
